services:
  app:
    image: ghcr.io/cat-ling/kitsune:latest  # Pull the latest image from GHCR
    container_name: kitsune-app
    environment:
      - NODE_ENV=production
      - PORT=54322
    ports:
      - "54322:54322"
    restart: unless-stopped
