name: docker-build

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'package.json'
      - 'package-lock.json'
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Git SHA
        id: get_sha
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/cat-ling/kitsune:${{ env.GIT_SHA }} -t ghcr.io/cat-ling/kitsune:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/cat-ling/kitsune:${{ env.GIT_SHA }}
          docker push ghcr.io/cat-ling/kitsune:latest
